### ISSUE TITLE
parse error for float arrays

### ISSUE THREAD

**Issue by andreasvef** [billdavidson/JSONUtil#1]
Example: Parsing of [1.1,2.2,-3.134598765,4.0] results in JSONParseException "Unrecognized data starting with: [1.1,2.2,-3.134598765,4.0] and the error marker pointing to the '.' in 4.0.
The reason seems to be in JAVASCRIPT_FLOATING_POINT_PAT, it does not accept ']' as terminator for a number, only comma and whitespace.

I think the last group of the pattern should be "([,\s\]}]|$)" instead of "([,\s}]|$)"

**Comment by billdavidson** [comment]
Thanks.  That will be fixed in the next release.

It's actually comma, whitespace and right curly brace (end of object) now.  Right bracket will be added.

**Comment by billdavidson** [comment]
I'm also adding this to the JUnit tests.

**Comment by billdavidson** [comment]
This is fixed in release 1.5 which is currently on GitHub and will be available shortly from the Maven Central Repository.

**Comment by billdavidson** [comment]
Fixed in release 1.8
