### ISSUE TITLE
Wrong handling of backslash in string values

### ISSUE THREAD

**Issue by andreasvef** [billdavidson/JSONUtil#3]
Backslashes in string values of a map (e.g. a Windows path) are not correctly escaped if the backslash together with the next char might be an escape sequence.. Example:
    map.put( "path", "c:\temp\next\path\realdummy.doc" );
is serialized as 
    {"path":"c:\temp\next\path\realdummy.doc"}
and after parsing it is printed as
"c: emp
ext\path
ealdummy.doc"

Tested with JSONUtil 1.7.,1 (Java7). See attachment for complete example
[JSONTest.zip](https://github.com/billdavidson/JSONUtil/files/377742/JSONTest.zip)

Expected: The string value must be returned unchanged.
If it is not possible to change the behavior due to compatibility issues, I would suggest to add a config setting for this.

**Comment by billdavidson** [comment]
Hmm.  I'll have to think on this one.  Compatibility could be an issue.

**Comment by billdavidson** [comment]
Thinking this through, passing most escapes through by default is the wrong behavior.  That should be moved to an option.  The only possible exception might be Unicode escapes, which are distinct and unlikely to occur when you don't want them.  I'm still thinking this one through.

**Comment by billdavidson** [comment]
Since the default behavior is wrong, I will be changing the default behavior so that all inline backslashes will be escaped by default.  The old behavior will still be available via a new config option called "passThroughEscapes".

**Comment by billdavidson** [comment]
This has been changed in the trunk branch.  New option added.  Will be in the next release.

**Comment by billdavidson** [comment]
This fix has been merged into the java7, java6 and java5 branches.

**Comment by billdavidson** [comment]
@andreasvef : If you would like to test the fix, you can download it here:

https://github.com/billdavidson/billdavidson.github.io/blob/master/JSONUtil/JSONUtil-1.8-java7-SNAPSHOT.jar

**Comment by billdavidson** [comment]
Fixed in release 1.8
