### ISSUE TITLE
JSON parsing fails if the JSON string contains newlines (\n)

### ISSUE THREAD

**Issue by andreasvef** [billdavidson/JSONUtil#5]
JSON parsing fails if the JSON string contains newlines (\r or \n) or tabs (\t) as whitespace, which is allowed according to RFC 4627.
The reason is probably line 462 in JSONParser:
      while ((codePoint >= 0) && (Character.isSpaceChar(codePoint))) 
I think this should be Character.isWhitespace(codePoint).

The LINE_SEPARATOR mentioned in javadoc of isSpaceChar is not one of the usual ones, but \u2028.

**Comment by andreasvef** [comment]
It works in JSONUtil 1.6

**Comment by billdavidson** [comment]
Bug.  Fix will be in next release.

**Comment by billdavidson** [comment]
Fix is in all branches.

**Comment by billdavidson** [comment]
Fixed in release 1.8
